### ISSUE TITLE
Allow sort by responses? and/or view only unresponded threads/ideas

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/community-platform#238]
As an admin this would help me to make sure I've addressed any new ideas/threads, and would also help me find any older, unaddressed posts.

I mostly want to be able to see what the newest ideas/threads are and make sure I've responded to everything that needs a response.

**Comment by brendanheywood** [comment]
Vaguely related to #458, but I think the real root cause here is deeply nested forums. Several decades of internet software has consistently proven these to just plain suck, look at any modern forum, discourse, stackoverflow, quora, facebook, github issues etc. In every case threads are either linear, or if nesting is allowed it only goes one extra level deep. Some of these started out with deep nesting and learnt the hard way and removed them.

Non-linear replies are notorious hard to keep track of conceptually and break the flow of reading, which in turn causes whole classes of usability problems, like not knowing what is new, trying to find an old comment, trying to mentally replay a conversation etc

Good reading: (Jeff Atwood of stackoverflow and discourse fame)
http://blog.codinghorror.com/web-discussions-flat-by-design/

**Comment by jbarrett** [comment]
Yeah, I think I only like threading on Usenet and mailing lists where the thread ordering presentation is separate from the message content. Munging the presentation of threading and message content together can get very noisy on busy discussions.

Also, anything that reduces complexity and reduces the number of columns in entities is good with me :)
