### ISSUE TITLE
when rate limiting a comment, give the user back the submitted text

### ISSUE THREAD

**Issue by zck** [duckduckgo/community-platform#818]
I submitted a comment on the [Help Describe Instant Answers](https://duck.co/forum/thread/14121/help-describe-instant-answers#thread-comments) page. Upon submitting it, I realized I wanted to submit another comment as a clarifying question.

I submitted this second comment, and was rate limited. However, the text of my question is now gone forever, so I have to rewrite it. My issue here isn't with rate limiting *itself*, rather the loss of the submitted text. A fix for this could be as simple as putting the comment text in the error page.

As a side note, I expect that this might be an issue on the page I linked above, since it's explicitly looking for multiple submissions per person.

**Comment by jbarrett** [comment]
Thanks @zck - this is caused by the cache-policy set in our headers (to stop someone using the back button to check out a cached profile page for instance)

This definitely should be applied more selectively - it's currently in server configs and sent with every request. I'll look into making a list of routes this should apply to and make it a code-level header inclusion - thinking any of the profile stuff in /my/*.

This should probably be a blacklist sort of feature, not whitelist or broad stroke since, as you point out, it's quite likely to cause annoyance in conjunction with other features.

**Comment by jbarrett** [comment]
This should be resolved.
